// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbwdvEkrIWoy7s-ro4gsqFg4fX0SIKXD8',
    appId: '1:444683843595:web:21168adc9118e63568af0e',
    messagingSenderId: '444683843595',
    projectId: 'onitama-game',
    authDomain: 'onitama-game.firebaseapp.com',
    storageBucket: 'onitama-game.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA98UVo0zdTyPbv-FYO78zJpLoRyzpBx7Y',
    appId: '1:444683843595:android:ec92a4f766b3253568af0e',
    messagingSenderId: '444683843595',
    projectId: 'onitama-game',
    storageBucket: 'onitama-game.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTyj6hB55dIt_jyniBQ9HR2kH0qYrCIEk',
    appId: '1:444683843595:ios:b7bc8483c811f6b468af0e',
    messagingSenderId: '444683843595',
    projectId: 'onitama-game',
    storageBucket: 'onitama-game.firebasestorage.app',
    iosBundleId: 'com.ltag.onitama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTyj6hB55dIt_jyniBQ9HR2kH0qYrCIEk',
    appId: '1:444683843595:ios:b7bc8483c811f6b468af0e',
    messagingSenderId: '444683843595',
    projectId: 'onitama-game',
    storageBucket: 'onitama-game.firebasestorage.app',
    iosBundleId: 'com.ltag.onitama',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbwdvEkrIWoy7s-ro4gsqFg4fX0SIKXD8',
    appId: '1:444683843595:web:963c670e3cd2bd6d68af0e',
    messagingSenderId: '444683843595',
    projectId: 'onitama-game',
    authDomain: 'onitama-game.firebaseapp.com',
    storageBucket: 'onitama-game.firebasestorage.app',
  );
}
